name: Workflow2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  getAllDirectories:
    runs-on: ubuntu-latest
    steps:
      - name: Get all directories
        run: |
          echo "Getting all directories"
          echo ls
          "$(ls ../..)" >> ./all_directories.txt
        shell: bash