name: Learning Workflows P1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi job
        run: echo "Hello World"
        shell: bash
  
  bye:
    runs-on: ubuntu-latest
    steps:
      - name: bye job
        run: echo "Bye Bye"
        shell: bash
